# Generated by Django 3.2.6 on 2021-08-15 11:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='starttime',
        ),
    ]
