# Generated by Django 3.2.6 on 2021-08-15 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_movie_poster'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('date', 'starttime')},
        ),
    ]
